- name: catalogue setup and installation
  hosts: catalogue
  become: yes
  tasks:
  - name: disbling existing and enabling nodejs
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y
  
  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop

  - name: recursively removing app directory
    ansible.builtin.file:
      path: /app
      state: absent
       
  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory
   
  - name: downloading file catalogue.zip
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /tmp
    
  - name: unarchile the zip file
    ansible.builtin.unarchive:
      src: https://roboshop-builds.s3.amazonaws.com/catalogue.zip
      dest: /app
      remote_src: yes


  - name: instaling dependencie
    ansible.builtin.command: npm install
    args:
      chdir: /app

  - name: copying catalogue.service
    ansible.builtin.copy:
      src: catalogue.service
      dest: /etc/systemd/system/catalogue.service

  - name: deamon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  # lets start after the data is loaded
   
  - name: copying mongodb.repo file
    ansible.builtin.copy:
       src: mongodb.repo
       dest: /etc/yum.repos.d/mongo.repo

  - name: installing mongodb-org-shell
    ansible.builtin.package: 
      name: mongodb-org-shell
      state: present

  - name: get the catalogue product count
    ansible.builtin.command: mongo --host mongodb.pjdevops.online --quiet --eval 'db = db.getSiblingDB("catalogue"); db.products.count()'
    register: product_count

  - name: print the product count
    ansible.builtin.debug:
      msg: "product count: {{product_count}}"
    
  - name: loading data from mongodb to catalogue
    ansible.builtin.command: mongo --host mongodb.pjdevops.online < /app/schema/catalogue.js
    when: product_count.stdout == "0"

  - name: enable and start catalogue
    ansible.builtin.service:
      name: catalogue
      state: started
      enabled: yes
