- name: setting up rabbitmq module
  hosts: rabbitmq
  become: yes
  tasks:
  - name: configure yum repos for rabbitmq
    ansible.builtin.command: curl -s https://packagecloud.io/install/repositories/rabbitmq/erlang/script.rpm.sh | bash

  - name: installing rabbitmq
    ansible.builtin.package:
      name: rabbitmq-server
      state: present

  - name: start and enable rabbitmq server
    ansible.builtin.service:
      name: rabbitmq-server
      state: started
      enabled: yes

  - name: setting up user and passwd
    ansible.builtin.shell: rabbitmqctl add_user roboshop roboshop123 ; rabbitmqctl set_permissions -p / roboshop ".*" ".*" ".*"