- name: setting up shipping component
  hosts: shipping
  become: yes
  vars: 
    mysql_password: RoboShop@1
  tasks:
  - name: instaling maven
    ansible.builtin.package:
      name: maven
      state: present
    
  - name: creating user roboshop
    ansible.builtin.user:
      name: roboshop
      state: present

  - name: recursively removing the directory
    ansible.builtin.file:
      name: /app
      state: absent
  
  - name: creating directory
    ansible.builtin.file:
      name: /app
      state: directory

  - name: downloading the application code shipping
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/shipping.zip
      dest: /tmp

  - name: unzip the shipping file
    ansible.builtin.unarchive:
      url: /tmp/shipping.zip
      dest: /app
      remote_src: yes
    

  - name: downloading the dependencies
    ansible.builtin.command: mvn clean package
    args: 
      chdir: /app

  - name: renaming shipping jar file
    ansible.builtin.command: mv target/shipping-1.0.jar shipping.jar
    args: 
      chdir: /app

  - name:  copying shipping.service
    ansible.builtin.copy:
      src: shipping.service
      dest: /etc/systemd/system/shipping.service
  
  - name: daemon reload
    ansible.builtin.systemd_service:
      daemon_reload: true
  
  - name: installing mysql client
    ansible.builtin.package:
      name: mysql
      state: present

  - name: checking cites schema exists or not
    ansible.builtin.command: mysql -h mysql.daws76s.online -uroot -p{{mysql_password}} -sN -e "SELECT COUNT(*) FROM INFORMATION_SCHEMA.SCHEMATA WHERE SCHEMA_NAME = 'cities'"
    register: cities_schema

  - name: debug the shippinmg count
    ansible.builtin.debug:
      msg: "cities count:{{cities_schema}}"

  - name: loading the shipping schema
    ansible.builtin.command: mysql -h mysql.pjdevops.online -uroot -p{{mysql_password}} < /app/schema/shipping.sql 
    when: cities_schema.stdout == "0"

  - name: start, enable the shipping
    ansible.builtin.service:
      name: shipping
      state: restarted
      enabbled: yes
