- name: user module set up and installation
  hosts: user
  become: yes
  tasks:
  - name: disabling old nodejs module  and enabling latest nodejs module
    ansible.builtin.shell: dnf module disable nodejs -y ; dnf module enable nodejs:18 -y

  - name: installing nodejs
    ansible.builtin.package:
      name: nodejs
      state: present

  - name: adding roboshop user
    ansible.builtin.user:
      name: roboshop

  - name: recursively removing app directory
    ansible.builtin.file:
      path: /app
      state: absent

  - name: creating app directory
    ansible.builtin.file:
      path: /app
      state: directory
  
  - name: downloading application code from url
    ansible.builtin.get_url:
      url: https://roboshop-builds.s3.amazonaws.com/user.zip
      dest: /tmp

  - name: unarchive user.zip
    ansible.builtin.unarchive:
      src: /tmp/user.zip
      dest: /app
      remote_src: yes
   
  - name: installing dependencies
    ansible.builtin.package:
      name: npm
      state: present
    args:
      chdir: /app

  - name: copying user.service file
    ansible.builtin.copy:
      src: user.service
      dest: /etc/systemd/system/user.service

  - name: daemon_reload
    ansible.builtin.systemd.service:
      daemon_reload: true
  
  - name: copiying mongo.repo
    ansible.builtin.copy:
      src: mongodb.repo
      dest: /etc/yum.repos.d/mongo.repo

  - name: installing mogodb client
    ansible.builtin.package:
      name: mongodb-org-shell
      state: present

  - name: get the user product count
    ansible.builtin.command: mongo --host mongodb.pjdevops.online --quiet --eval 'db = db.getSiblingDB("users"); db.users.count()'
    register: user_count

  - name: printing the user count
    ansible.builtin.debug:
      msg: "printing the user count {{user_count}}"

  - name: loading /app/schema/catalogue.js
    ansible.builtin.command: mongo --host mongodb.pjdevops.online < /app/schema/user.js
    when: user_count.stdout == "0"

  - name: start, enable user services
    ansible.builtin.service:
      name: user
      state: restarted
      enabled: yes